private CSVPrinter printWithHeaderComments(final StringWriter sw, final Date now, final CSVFormat baseFormat)
    throws IOException {
  CSVFormat format = baseFormat;
  // Use withHeaderComments first to test CSV-145
  format = format.withHeaderComments("Generated by Apache Commons CSV 1.1", now);
  format = format.withCommentMarker('#');
  format = format.withHeader("Col1", "Col2");
  final CSVPrinter csvPrinter = format.print(sw);
  csvPrinter.printRecord("A", "B");
  csvPrinter.printRecord("C", "D");
  csvPrinter.close();
  return csvPrinter;
}